network.host: 0.0.0.0
http.port: 9200
bootstrap.memory_lock: true
discovery.type: single-node
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false