version: "3"

services:

  elasticsearch:
    image: elasticsearch:5.1.2
    container_name: elastic
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - $PWD/configs/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - fablo_network_202308300640_basic

  logstash:
    image: logstash:5.1.2
    container_name: logstash
    command: logstash -f /config/
    environment:
      - JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - $PWD/configs/logstash/config:/config
    networks:
      - fablo_network_202308300640_basic
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:5.1.2
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - $PWD/configs/kibana/kibana.yml:/etc/kibana/kibana.yml
    networks:
      - fablo_network_202308300640_basic
    depends_on:
      - elasticsearch

networks:
  fablo_network_202308300640_basic:
    external: true
