version: '3.3'

networks:
  fabric:
    driver: overlay
    attachable: true

services:
  logstash:
    image: logstash:7.5.1
    environment:
    - LOGSPOUT=ignore
    - LOG_LEVEL=info
    volumes:
    - ~/configs/logstash/jvm.options:/usr/share/logstash/config/jvm.options
    - ~/configs/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    - ~/configs/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    expose:
    - 5000
    networks:
    - fabric
    deploy:
      mode: replicated
      replicas: 1