- pipeline.id: input-pipeline
  path.config: "/usr/share/logstash/pipeline/input.conf"
  pipeline.workers: 1

- pipeline.id: peer-pipeline
  path.config: "/usr/share/logstash/pipeline/peer.conf"
  pipeline.workers: 1