- pipeline.id: input-pipeline
  path.config: "/usr/share/logstash/pipeline/input.conf"
  pipeline.workers: 1

- pipeline.id: peer-pipeline
  path.config: "/usr/share/logstash/pipeline/peer.conf"
  pipeline.workers: 1

- pipeline.id: orderer-pipeline
  path.config: "/usr/share/logstash/pipeline/orderer.conf"
  pipeline.workers: 1

- pipeline.id: default-pipeline
  path.config: "/usr/share/logstash/pipeline/default.conf"
  pipeline.workers: 1

# - pipeline.id: output-pipeline
#   path.config: "/usr/share/logstash/pipeline/output.conf"
#   pipeline.workers: 1